### ISSUE TITLE
docpad-plugin-less@2.5.0 hangs with Docpad v6.79.4

### ISSUE THREAD

**Issue by Aglezabad** [docpad/docpad-plugin-less#18]
Good afternoon:

I've tried the last update of Docpad and your plugin and I have this problem: Docpad hangs with docpad-plugin-less 2.5.0 but it works perfectly with docpad-plugin-less 2.4.1.

I don't know why it begins to cause problems on my site project. I give you the next information:

- Plugins used: analytics, api, authentication, cleanurls, copy, ect, gist, imagin, less, marked, moment, paged, related, sitemap

- [Log of Docpad with less plugin 2.4.1](https://github.com/docpad/docpad-plugin-less/files/893051/docpad-debug241.txt)
- [Log of Docpad with less plugin 2.5.0](https://github.com/docpad/docpad-plugin-less/files/893052/docpad-debug250.txt)

If you need anything else, just tell me.
Thank you.

**Comment by balupton** [comment]
thanks, looking into it

**Comment by balupton** [comment]
@Aglezabad maybe I can remote in to debug? If so, ping me on our slack https://slack.bevry.me

**Comment by sdomagala** [comment]
I think this will solve this issue #19

**Comment by balupton** [comment]
@Aglezabad nevermind, @sdomagala has come to the rescue!

**Comment by balupton** [comment]
@Aglezabad the just released v2.5.1 should fix this,  thanks to @sdomagala

**Comment by Aglezabad** [comment]
You are great. Thank you very much. Now it's working flawlessly.
Best regards.
